
--Batch Mode Memory Grant Feedback
ALTER DATABASE current SET COMPATIBILITY_LEVEL  = 150; 

ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF

ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON
OPTION (USE HINT ('DISABLE_BATCH_MODE_MEMORY_GRANT_FEEDBACK'));


--Adaptive Join Operator
--Enable 
ALTER DATABASE current SET COMPATIBILITY_LEVEL  = 150; 
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_ADAPTIVE_JOINS = OFF;
--Disable 
ALTER DATABASE SCOPED CONFIGURATION SET DISABLE_BATCH_MODE_ADAPTIVE_JOINS = ON;
OPTION(USE HINT('DISABLE_BATCH_MODE_ADAPTIVE_JOINS'));




--Batch
--Enabling 
ALTER DATABASE current SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
OPTION (USE HINT('ALLOW_BATCH_MODE'));


--Disabling
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = OFF;
OPTION (USE HINT('DISALLOW_BATCH_MODE'))

--APPROX_COUNT_DISTINCT
SELECT APPROX_COUNT_DISTINCT(pid) FROM dbo.A;
SELECT COUNT(DISTINCT(pid)) FROM dbo.A;

--Enabling/Disabling Table Variable Deferred Compilation
--Enable 
ALTER DATABASE current SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;

--Disable 
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = OFF;
OPTION (USE HINT('DISABLE_DEFERRED_COMPILATION_TV'));


--UDF inline
SELECT CONCAT(SCHEMA_NAME(o.schema_id),'.',o.name),is_inlineable FROM sys.sql_modules m INNER JOIN sys.objects o ON o.object_id = m.object_id WHERE o.type = 'FN'

--Enabling/Disabling Scalar UDF Inlining

--Enable
ALTER DATABASE current SET COMPATIBILITY_LEVEL = 150;
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
CREATE OR ALTER FUNCTION dbo.getMaxOrderDate(@CustID INT) RETURNS DATETIME WITH INLINE = ON

--Disable 
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = OFF;
OPTION (USE HINT('DISABLE_TSQL_SCALAR_UDF_INLINING'));
CREATE OR ALTER FUNCTION dbo.getMaxOrderDate(@CustID INT) RETURNS DATETIME WITH INLINE = OFF;