/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

IF TYPE_ID('[dbo].[ud_TempForRedQuery]') IS NOT NULL
	DROP TYPE [dbo].[ud_TempForRedQuery];

GO
CREATE TYPE [dbo].[ud_TempForRedQuery] AS TABLE
(
[Id] [int] NULL,
[Name] [nvarchar] (4000) COLLATE Persian_100_CS_AI NULL,
[CreatedTime] [datetime] NULL
)
GO
