SELECT * FROM Products
UNION -- 77+2 = 79
SELECT * FROM Cat1

SELECT * FROM Products
UNION ALL -- 77+12 = 89
SELECT * FROM Cat1

SELECT * FROM Products
INTERSECT  --10
SELECT * FROM Cat1


SELECT * FROM Products
EXCEPT  -- 77-10 = 67
SELECT * FROM Cat1


SELECT * FROM Cat1
EXCEPT  -- 12-10=2
SELECT * FROM Products
