SELECT DB.name AS 'DATABASE Name',
       MF.type_desc AS FileType,
       MF.physical_name AS Location,
       DB.state_desc AS DataBaseState,
       DB.compatibility_level,
       DB.collation_name,
       DB.user_access_desc,
       MF.size,
       MF.max_size,
       MF.growth,
       MF.is_media_read_only,
       MF.is_read_only,
       MF.is_percent_growth,
       MF.is_name_reserved,
       MF.is_persistent_log_buffer,
       DB.owner_sid,
       DB.create_date,
       DB.is_read_only,
       DB.is_auto_close_on,
       DB.is_auto_shrink_on,
       DB.state,
       DB.state_desc,
       DB.is_in_standby,
       DB.is_cleanly_shutdown,
       DB.is_supplemental_logging_enabled,
       DB.snapshot_isolation_state,
       DB.snapshot_isolation_state_desc,
       DB.is_read_committed_snapshot_on,
       DB.recovery_model,
       DB.recovery_model_desc,
       DB.page_verify_option,
       DB.page_verify_option_desc,
       DB.is_auto_create_stats_on,
       DB.is_auto_create_stats_incremental_on,
       DB.is_auto_update_stats_on,
       DB.is_auto_update_stats_async_on,
       DB.is_ansi_null_default_on,
       DB.is_ansi_nulls_on,
       DB.is_ansi_padding_on,
       DB.is_ansi_warnings_on,
       DB.is_arithabort_on,
       DB.is_concat_null_yields_null_on,
       DB.is_numeric_roundabort_on,
       DB.is_quoted_identifier_on,
       DB.is_recursive_triggers_on,
       DB.is_cursor_close_on_commit_on,
       DB.is_local_cursor_default,
       DB.is_fulltext_enabled,
       DB.is_trustworthy_on,
       DB.is_db_chaining_on,
       DB.is_parameterization_forced,
       DB.is_master_key_encrypted_by_server,
       DB.is_query_store_on,
       DB.is_published,
       DB.is_subscribed,
       DB.is_merge_published,
       DB.is_distributor,
       DB.is_sync_with_backup,
       DB.service_broker_guid,
       DB.is_broker_enabled,
       DB.log_reuse_wait,
       DB.log_reuse_wait_desc,
       DB.is_date_correlation_on,
       DB.is_cdc_enabled,
       DB.is_encrypted,
       DB.is_honor_broker_priority_on,
       DB.target_recovery_time_in_seconds,
       DB.is_memory_optimized_elevate_to_snapshot_on,
       DB.is_federation_member,
       DB.is_remote_data_archive_enabled,
       DB.is_mixed_page_allocation_on,
       DB.is_temporal_history_retention_enabled
FROM sys.master_files AS MF
    INNER JOIN sys.databases AS DB
        ON DB.database_id = MF.database_id;