IF OBJECT_ID('[dba].[Who]') IS NOT NULL
	DROP PROCEDURE [dba].[Who];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE       PROCEDURE [dba].[Who]
    @SPID INT = 0
AS
BEGIN
    SET @SPID = NULLIF(@SPID, 0);
    EXEC sp_who2 @SPID;
END;
GO
