
USE tempdb
GO
--هنگام ایجاد جدولFILLFACTOR تنظیم 
CREATE TABLE T2
(
	ID int IDENTITY NOT NULL,
	Filler char(8000) NULL, 
	PRIMARY KEY CLUSTERED (ID DESC) WITH(FILLFACTOR=85,PAD_INDEX=ON) --نزولی
)
GO
--ایندکس Rebuild هنگام FILLFACTOR تنظیم 
ALTER INDEX ALL ON T2 REBUILD WITH(FILLFACTOR=85,PAD_INDEX=ON)

